kind: pipeline
type: docker
name: default

workspace:
  base: /kileed
  path: src

steps:
- name: setup-workspace
  image: stjv/kileed-build-env
  commands:
  - bash ci/setup-workspace.sh

- name: pylint
  image: stjv/killeed-build-env:latest
  commands:
  - bash ci/pylint.sh
  depends_on: [ 'setup-workspace' ]

- name: pydocstyle
  image: stjv/killeed-build-env:latest
  commands:
  - ./.env/bin/pydocstyle
  depends_on: [ 'setup-workspace' ]

- name: eslint
  image: stjv/killeed-build-env:latest
  commands:
  - bash ci/eslint.sh
  depends_on: [ 'setup-workspace' ]

- name: api-unit-tests
  image: stjv/killeed-build-env:latest
  commands:
  - bash ci/api-unit-tests.sh
  depends_on: [ 'setup-workspace' ]

- name: ui-unit-tests
  image: stjv/killeed-build-env:latest
  commands:
  - bash ci/ui-unit-tests.sh
  depends_on: [ 'setup-workspace' ]

- name: build-ui
  image: stjv/killeed-build-env:latest
  commands:
  - bash ci/build-ui.sh
  depends_on:
  - 'pylint'
  - 'pydocstyle'
  - 'eslint'
  - 'api-unit-tests'
  - 'ui-unit-tests'

- name: e2e-tests
  image: ubuntu:latest
  commands:
  - bash ci/e2e-tests.sh
  depends_on: ['build-ui']
