kind: pipeline
type: docker
name: default

workspace:
  base: /kileed
  path: src

steps:
- name: Setup Workspace
  image: ubuntu:latest
  commands:
  - bash setup-env.sh

- name: Pylint
  image: ubuntu:latest
  commands:
  - ./.env/bin/pylint kileed
  depends_on: [ 'Setup Workspace' ]

- name: API Unit Tests
  image: ubuntu:latest
  commands:
  - ./.env/bin/python manage.py test kileed.tests.unit
  depends_on: [ 'Setup Workspace' ]

- name: Pydocstyle
  image: ubuntu:latest
  commands:
  - ./.env/bin/pydocstyle
  depends_on: [ 'Setup Workspace' ]

- name: ESLint
  image: ubuntu:latest
  commands:
  - ./.env/bin/node
      ./kileed/ui/node_modules/eslint/bin/eslint.js
      kileed/ui/src/**/*.{js,vue}
  depends_on: [ 'Setup Workspace' ]

- name: Build UI
  image: ubuntu:latest
  commands:
  - bash ci/build-ui.sh
  depends_on:
  - 'Pylint'
  - 'API Unit Tests'
  - 'Pydocstyle'
  - 'ESLint'

- name: E2E tests
  image: ubuntu:latest
  commands:
  - bash ci/e2e-tests.sh
  depends_on: ['Build UI']