kind: pipeline
type: docker
name: default

workspace:
  base: /kileed
  path: src

steps:
- name: Setup Workspace
  image: python:3.7
  commands:
  - bash setup-env.sh

- name: Pylint
  image: python:3.7
  commands:
  - ./.env/bin/pylint kileed
  depends_on: [ 'Setup Workspace' ]

- name: API Unit Tests
  image: python:3.7
  commands:
  - ./.env/bin/python manage.py test
  depends_on: [ 'Setup Workspace' ]

- name: Pydocstyle
  image: python:3.7
  commands:
  - ./.env/bin/pydocstyle
  depends_on: [ 'Setup Workspace' ]

- name: ESLint
  image: python:3.7
  commands:
  - ./kileed/ui/node_modules/.bin/eslint kileed/ui/src/**/*.{js,vue}
  depends_on: [ 'Setup Workspace' ]

- name: Publish
  image: python:3.7
  depends_on:
  - 'Pylint'
  - 'API Unit Tests'
  - 'Pydocstyle'
  - 'ESlint'