kind: pipeline
type: docker
name: default

# Setup steps
steps:
- name: refresh-build-image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker build -t kileed-build-image:latest -f scripts/drone-dockerfile.conf .

- name: build
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh build
  depends_on: [ 'setup' ]

# Lint
- name: api-lint
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh api-lint
  depends_on: [ 'build' ]

- name: ui-lint
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh ui-lint
  depends_on: [ 'build' ]

# Tests
- name: api-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh api-tests
  depends_on: [ 'build' ]

- name: ui-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh ui-tests
  depends_on: [ 'build' ]

- name: e2e-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash scripts/drone.sh e2e-tests
  depends_on: [ 'build' ]

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
