kind: pipeline
type: docker
name: default

workspace:
  base: /kileed
  path: src

steps:
- name: Setup Workspace
  image: python:3.7
  commands:
  - pip install virtualenv
  - ./.env/bin/pip install -r requirements.txt
  - ./.env/bin/pip install pylint

steps:
- name: Pylint
  image: python:3.7
  commands:
  - ./.env/bin/pylint kileed
