kind: pipeline
type: docker
name: default

# Setup steps
steps:
- name: refresh-build-image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker build -t kileed-build-image:latest -f scripts/drone-dockerfile.conf .

# API
- name: api-lint
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh api-lint
  depends_on: [ 'refresh-build-image' ]

- name: api-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh api-tests
  depends_on: [ 'refresh-build-image' ]

# UI
- name: ui-setup
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh ui-setup
  depends_on: [ 'refresh-build-image' ]

- name: ui-lint
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh ui-lint
  depends_on: [ 'ui-setup' ]

- name: ui-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh ui-tests
  depends_on: [ 'ui-setup' ]

- name: ui-build
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh ui-build
  depends_on: [ 'ui-setup' ]

# E2E
- name: e2e-tests
  image: kileed-build-image
  pull: if-not-exists
  commands:
  - bash .drone.sh e2e-tests
  depends_on: [ 'ui-build' ]

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
